// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ZsdkVPRuEtpXYx1e7e7W648AbtwktV8',
    appId: '1:756488204699:web:111593c9afaf4558a3f13e',
    messagingSenderId: '756488204699',
    projectId: 'fluttertest20231118',
    authDomain: 'fluttertest20231118.firebaseapp.com',
    storageBucket: 'fluttertest20231118.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACtRp7H1heItF1pUPHEJWIXz4gNp8mQXU',
    appId: '1:756488204699:android:343b2a3315fb6998a3f13e',
    messagingSenderId: '756488204699',
    projectId: 'fluttertest20231118',
    storageBucket: 'fluttertest20231118.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE2oboiATC2nvAUF95h844qek7mwdLLtk',
    appId: '1:756488204699:ios:f0aff1399f46c158a3f13e',
    messagingSenderId: '756488204699',
    projectId: 'fluttertest20231118',
    storageBucket: 'fluttertest20231118.appspot.com',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE2oboiATC2nvAUF95h844qek7mwdLLtk',
    appId: '1:756488204699:ios:5117eb11f5cf33a3a3f13e',
    messagingSenderId: '756488204699',
    projectId: 'fluttertest20231118',
    storageBucket: 'fluttertest20231118.appspot.com',
    iosBundleId: 'com.example.todoFirebase.RunnerTests',
  );
}
